main: com.gmail.markushygedombrowski.HLVagtPoster
version: "1.0"
name: HLVagtPoster
depend: [Vault,WorldGuard,WorldEdit,HLUtils,HolographicDisplays,HLvagt,HLVagt]
commands:
  createvagtpost:
    description: "create vagtpost"
    aliases: ["replacevagtpost","deletevagtpost"]
  reloadvagtpost:
    description: "reload vagtpost"
    aliases: ["rlvagtpost"]
  sethead:
    description: "set head"
    aliases: ["sethead"]
